sudo: required

cache: bundler

services:
  - docker

env:
  global:
    - secure: Zg0SR/kkln9OTxJENW3xNl3OWWKtt5j+b0C7OSjG05cr0RR4NeWAseLW6U3fwuol5lq7bb5sAOyiGqTwifcNC9LjPkECY/vaCaspZD8mRBbOi8P1fzdZBRjAh/SiVFd3guMs/eHtdi99JMZSTWnzQ5FZAnsKpmhaXIsyjerI1YnD7rvyoBdBP/wRiW7GPOKLGahNP3AKlRSGUchIiFkTGt8Xk+USjqNLs+sJkxXAUCiQuXXIdTgo/BVHsZcQ/jmC3AVP9fn7SkXTWB4y21FPM8MTIeAeS62xQm6lYIaslEHLFxpGfzqIQJUg+0fv4N/i4gLaWu4nVvKrcg6chExn+iY+mvw9PGF/AGP4zuyMWyEVg8zIttHGOW+b8sPpeRcbK32px66b/UxeXj5xkzqSRlObyoGHv+5JeDCtbUcZK5eu0DUWJ+XFoK5QrtILTaQ7XmpbRyGUIJHJD9Va7ZwhXPVyLS5gej0axM6/RqThCNoI4fuImPCSuEa8uNsCHwusrlS3r+vDyxPXTH2gYVoIO7aOOGCf8IBLSIH98Xk5FUKKA/7ucx4wYMVLhdtfTkBas9zv7adiwfKQUjkOTdAtpz+7Q4T6vM8Eh1IJIe6rQKpR4weDlAEP0Mko3BnPjDT5qVTsNNSPbh1kzrsf+hv0P4CJZ6ArGhwPiWrPJ58BhXE=
    - secure: Pq3zHd4gCnM40GQIgEq4tvJV1iYvJM1vkxZ8+SXwQXCubQgrEV8PpPcBAEei2l8VTeulKfAIt+Kvj6lXrwU2lIXZbpRpZj8CDc86xvwtg0yEBcCNvTm9A6U2CoY4lf6a17gnWXAr+MSLs9R/RSZFuTZfu5h+qq8qZyPA8Dre6D20RR4s1uz+pNINkxH94MoT6yv5ArQBpbj2flLup27qVzjZoEFelANK598XOcGWP5KSF0ATrsrTIzuQ2l6J0B0czq9OI7V8YX0mY4zddrDd+DT3/W0+KlrMB3DvWoqrD4B1g3Oyl577kLn4VSp7uodadFO4wt0/WoLaCDD33Xt3fZr6GYhc6pss6/zpQ2GGsHoqS2nnb+pWzVgQGFdGZtwzRkodw8XDGpySEqFq6jSLe39y9TYc2Jz5P9WypfI+OcpPJmDrgjouwz5AlyHz3wj+Il4XYR8d6rkYQCL72yDjJW6YC6MDAy3X2tgRSriodbKmZPoBZkObcI5P2OrSQSybMcg4G0noC2QL6y3cONQcUwApHoW+lFGO6YHBHsbMFHHVTwzPzrHMr5t8azaDJ+eogvLBl0q2ZJSef8xD8uLkDttoKVC5YmebiFDmeFMgkRLfqKiw/WM/LF6et9Rd5W/xl1MlyedCQl+qhDNeh6y3LAPnEtXqyaPf0gc3fJ2H188=

script:
  - bash docker-build.sh
  - bash docker-test.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images
